class GameConfig:
    
    # Game window dimensions
    SCREEN_WIDTH = 320*3
    SCREEN_HEIGHT = 240*3
    
    FPS = 60
    
    # Game window title
    SCREEN_TITLE = "Py金庸群侠传"
    GAME_TITLE = "Py金庸群侠传"
    
    # Sub Scene setting
    
    SUB_SCENE_WIDTH = 320
    SUB_SCENE_HEIGHT = 240
    
    SUB_SCENE_NUMBER = 84
    SUB_SCENE_DATA_LAYER_NUMBER = 6
    SUB_SCENE_LAYER_DATA_LENGTH = 4096
    SUB_SCENE_ALL_LAYER_DATA_LENGTH = SUB_SCENE_NUMBER * SUB_SCENE_DATA_LAYER_NUMBER * SUB_SCENE_LAYER_DATA_LENGTH

    SUB_SCENE_EVENT_NUMBER_PER_SCENE = 200
    SUB_SCENE_EVENT_DATA_LENGTH = 11

    SUB_SCENE_ALL_EVENT_DATA_LENGTH = SUB_SCENE_NUMBER * SUB_SCENE_EVENT_NUMBER_PER_SCENE * SUB_SCENE_EVENT_DATA_LENGTH
    
    
    SUB_SCENE_GRID_NUMBER_W = 64
    SUB_SCENE_GRID_NUMBER_H = 64
    
    SUB_SCENE_GRID_SIZE_W = 36
    SUB_SCENE_GRID_SIZE_H = 18
    